export component MainWindow inherits Window {
    title : "Slint ESP32s3 Example" ;
    
    preferred-width : 320px;
    preferred-height : 240px;

    Text {
        text: "hello world";
        color: green;
    }
}

// import { Button, VerticalBox } from "std-widgets.slint";
// export component MainWindow inherits Window {
//     width: 200px;
//     height: 100px;
//     VerticalBox {
//         label := Text {
//             text: "Button not clicked";
//         }
//         Button {
//             text: "Click Me";
//             clicked => {
//                 label.text = " Button clicked";
//             }
//         }
//     }
// }